import { Prompt } from "@/types/prompt";

export const mockPrompts: Prompt[] = [
  {
    id: "1",
    title: "Ultra-Realistic Portrait Generator",
    description: "Create hyper-realistic portraits with studio lighting and professional composition",
    content: "Generate a photorealistic portrait of [subject], studio lighting, 85mm lens, shallow depth of field, professional photography, high detail, 8k resolution",
    category: "image",
    tags: ["portrait", "photography", "realistic", "trending"],
    votes: 234,
    author: "Sarah Chen",
    createdAt: "2024-01-15",
    isTrending: true,
  },
  {
    id: "2",
    title: "YouTube Script Writer Pro",
    description: "Generate engaging YouTube video scripts with hooks, storytelling, and CTAs",
    content: "Write a YouTube video script about [topic]. Include: 1) Attention-grabbing hook in first 10 seconds, 2) Clear structure with timestamps, 3) Engaging storytelling, 4) Call-to-action at end. Target audience: [audience]. Video length: [duration].",
    category: "text",
    tags: ["youtube", "scripting", "content", "trending"],
    votes: 189,
    author: "Marcus Rivera",
    createdAt: "2024-01-14",
    isTrending: true,
  },
  {
    id: "3",
    title: "Cinematic B-Roll Prompt",
    description: "Generate stunning cinematic b-roll footage for your video projects",
    content: "Create cinematic b-roll footage of [scene], golden hour lighting, slow motion, shallow depth of field, color graded, professional cinematography, 4K",
    category: "video",
    tags: ["cinematic", "b-roll", "video", "production"],
    votes: 156,
    author: "Emma Watson",
    createdAt: "2024-01-13",
  },
  {
    id: "4",
    title: "React Component Generator",
    description: "AI-powered React component creation with TypeScript and best practices",
    content: "Generate a React component for [component description]. Requirements: TypeScript, functional component, proper types, accessibility, responsive design, clean code. Include props interface and documentation.",
    category: "code",
    tags: ["react", "typescript", "component", "trending"],
    votes: 298,
    author: "David Park",
    createdAt: "2024-01-12",
    isTrending: true,
  },
  {
    id: "5",
    title: "Email Automation Workflow",
    description: "Create sophisticated email automation sequences for marketing campaigns",
    content: "Design an email automation workflow for [campaign goal]. Include: 1) Welcome sequence, 2) Nurture emails, 3) Re-engagement series, 4) Segmentation logic, 5) A/B testing recommendations. Target: [audience].",
    category: "automation",
    tags: ["email", "marketing", "automation", "workflow"],
    votes: 134,
    author: "Lisa Thompson",
    createdAt: "2024-01-11",
  },
  {
    id: "6",
    title: "Fantasy Character Design",
    description: "Create unique fantasy characters with detailed descriptions and backstories",
    content: "Design a fantasy character: [character type], detailed appearance, magical abilities, backstory, personality traits, digital art style, concept art, highly detailed, trending on artstation",
    category: "image",
    tags: ["fantasy", "character", "art", "design"],
    votes: 201,
    author: "Alex Kim",
    createdAt: "2024-01-10",
  },
  {
    id: "7",
    title: "SQL Query Optimizer",
    description: "Generate optimized SQL queries with performance best practices",
    content: "Write an optimized SQL query to [task description]. Include: proper indexing suggestions, query explanation, performance considerations, and alternative approaches if applicable. Database: [database type].",
    category: "code",
    tags: ["sql", "database", "optimization", "backend"],
    votes: 167,
    author: "Michael Zhang",
    createdAt: "2024-01-09",
  },
  {
    id: "8",
    title: "Product Launch Video Script",
    description: "Compelling video scripts for product launches and announcements",
    content: "Create a product launch video script for [product name]. Duration: 60-90 seconds. Include: problem statement, solution showcase, key features (max 3), social proof, strong CTA. Tone: [tone]. Target: [audience].",
    category: "video",
    tags: ["product", "launch", "marketing", "script"],
    votes: 142,
    author: "Jennifer Lee",
    createdAt: "2024-01-08",
  },

  // Extended prompts (author set to "developer", createdAt set to today's date)
  {
    id: "101",
    title: "AI Resume Builder (ATS-Optimized)",
    description: "Generate an ATS-friendly, role-specific resume tailored to job description keywords.",
    content: "Create a concise, ATS-optimized resume for [full name]. Target role: [job title]. Experience: [years]. Key achievements: [achievements]. Include: professional summary, skills (keyword-mapped to JD), experience bullets with metrics, education, and a short cover note.",
    category: "text",
    tags: ["resume", "career", "job", "ats", "professional"],
    votes: 412,
    author: "developer",
    createdAt: "2025-11-03",
    isTrending: true,
  },
  {
    id: "102",
    title: "SEO Blog Post Outline + Meta",
    description: "High-ROI blog outline with keywords, headings, meta description and internal link ideas.",
    content: "Generate an SEO-optimized blog post outline for topic: [topic]. Include: target keyword list, suggested title variations, H1-H4 headings with brief notes, meta description (<=155 chars), suggested internal links and FAQs for schema markup.",
    category: "text",
    tags: ["seo", "content", "blog", "marketing"],
    votes: 287,
    author: "developer",
    createdAt: "2025-11-03",
  },
  {
    id: "103",
    title: "Social Media Ad Copy + Variants",
    description: "Multiple short ad copies optimized per platform and CTA testing variations.",
    content: "Write 6 ad copy variants for product: [product name]. Platforms: Instagram (story + feed), Facebook, LinkedIn, Google Responsive. Include: headline, body (<=125 chars for mobile), CTA variations, and 2 short A/B test hypotheses.",
    category: "automation",
    tags: ["ads", "marketing", "facebook", "instagram", "copy"],
    votes: 198,
    author: "developer",
    createdAt: "2025-11-03",
    isTrending: true,
  },
  {
    id: "104",
    title: "Prompt Engineering — Image Style Transfer",
    description: "Create a detailed prompt for image generation to transfer a specific art style.",
    content: "Generate an image prompt: subject: [subject]. Style reference: [artist/style]. Requirements: camera/lens (optional), lighting, color palette, texture details, composition rules, negative prompts to avoid [undesired elements], final resolution target.",
    category: "image",
    tags: ["prompt-engineering", "image", "style-transfer", "art"],
    votes: 259,
    author: "developer",
    createdAt: "2025-11-03",
  },
  {
    id: "105",
    title: "YouTube Short Script + Hook Pack",
    description: "Fast, viral-ready short video scripts with 3-second hooks and captions.",
    content: "Write 5 short-form video scripts (15-60s) for topic: [topic]. Each script: 1-sentence hook (<=3s), main idea, punchline, caption text, suggested on-screen text, recommended thumbnail idea.",
    category: "video",
    tags: ["youtube", "shorts", "hook", "script", "social"],
    votes: 221,
    author: "developer",
    createdAt: "2025-11-03",
    isTrending: true,
  },
  {
    id: "106",
    title: "Product Spec to React Component",
    description: "Auto-generate a TypeScript React component from a short UI spec with props and docs.",
    content: "Create a functional React + TypeScript component for: [component name]. Spec: [brief spec]. Requirements: prop types/interfaces, accessibility (aria), responsive layout, example usage and storybook snippet.",
    category: "code",
    tags: ["react", "typescript", "component", "ui", "frontend"],
    votes: 346,
    author: "developer",
    createdAt: "2025-11-03",
  },
  {
    id: "107",
    title: "Customer Support Chatbot Flow",
    description: "Design a helpful customer support chatbot flow with intents, sample utterances and fallback.",
    content: "Design chatbot flow for [product/service]. Include: main intents, user utterance examples, bot replies (short + detailed), slot filling, escalation to human, fallback responses, and suggested success metrics.",
    category: "automation",
    tags: ["chatbot", "support", "automation", "ux"],
    votes: 174,
    author: "developer",
    createdAt: "2025-11-03",
  },
  {
    id: "108",
    title: "Data Visualization Brief for Designers",
    description: "Turn raw data and KPIs into a clear visualization brief designers can implement.",
    content: "You are given dataset: [describe columns]. Objective: show [insight]. Provide: recommended chart types, color/legend rules, axis choices, aggregation logic, annotations to highlight, and export sizes (web / print).",
    category: "code",
    tags: ["data-viz", "ux", "design", "charts"],
    votes: 132,
    author: "developer",
    createdAt: "2025-11-03",
  },
  {
    id: "109",
    title: "Cold Email Sequence (B2B)",
    description: "A four-step cold email sequence with personalization tokens and follow-ups that convert.",
    content: "Write a 4-email B2B outreach sequence for offer: [offer]. Target persona: [title/industry]. Include personalization templates, subject lines, CTA options (demo, calendar, whitepaper), and timing recommendations.",
    category: "automation",
    tags: ["email", "b2b", "outreach", "sales"],
    votes: 205,
    author: "developer",
    createdAt: "2025-11-03",
  },
  {
    id: "110",
    title: "On-Brand Logo Concept Prompts",
    description: "Generate creative logo concepts and rationale for a brand brief.",
    content: "Brand: [brand name]. Values: [values]. Audience: [audience]. Generate 6 logo concept prompts (short descriptions) including color palette suggestions, shape language, and one-line rationale for each concept suitable for a designer to sketch.",
    category: "image",
    tags: ["branding", "logo", "design", "creative"],
    votes: 164,
    author: "developer",
    createdAt: "2025-11-03",
  },
  {
    id: "111",
    title: "Performance-Ready SQL + Index Plan",
    description: "Create a performant SQL query plus indexing and partitioning suggestions for large tables.",
    content: "Write an optimized SQL for task: [task]. DB: [Postgres/MySQL/Redshift]. Include: explain plan notes, index recommendations, partition strategy, expected complexity, and one alternative approach (materialized view, denormalization).",
    category: "code",
    tags: ["sql", "database", "optimization", "backend"],
    votes: 198,
    author: "developer",
    createdAt: "2025-11-03",
  },
  {
    id: "112",
    title: "Mobile App Onboarding Copy + Flow",
    description: "Concise onboarding screens with microcopy to boost activation and retention.",
    content: "Create 5 onboarding screens for mobile app: [app name]. Include microcopy for headline, description, tip copy, optional progress indicators, permissions copy (why we ask), and a short success message.",
    category: "text",
    tags: ["ux", "copy", "onboarding", "mobile"],
    votes: 149,
    author: "developer",
    createdAt: "2025-11-03",
    isTrending: true,
  },
  {
    id: "113",
    title: "AI-Powered Lesson Plan Generator",
    description: "Create a structured lesson plan with objectives, activities, and assessments for any grade.",
    content: "Generate a lesson plan for subject: [subject], grade: [grade]. Include learning objectives, warm-up activity, core activities (with timings), formative assessment, homework, and differentiation tips.",
    category: "text",
    tags: ["education", "lesson", "teaching", "curriculum"],
    votes: 120,
    author: "developer",
    createdAt: "2025-11-03",
  },
  {
    id: "114",
    title: "Pitch Deck Slide-by-Slide Content",
    description: "Create content for each slide of a startup pitch deck tailored to investor type.",
    content: "Startup: [name]. Stage: [seed/series A]. Market: [market]. Provide slide-by-slide content for 10 slides (cover, problem, solution, market, traction, business model, team, financials, ask), plus speaker notes and 3 key metrics to highlight.",
    category: "text",
    tags: ["pitch", "startup", "investor", "presentation"],
    votes: 273,
    author: "developer",
    createdAt: "2025-11-03",
    isTrending: true,
  },
  {
    id: "115",
    title: "Cinematic Scene Direction for VFX",
    description: "Detailed scene direction for shooting plates and VFX-friendly footage.",
    content: "Describe how to shoot scene: [scene]. Provide camera movement notes, lens choices, plate coverage, lighting references, crowd/props notes, green-screen directions, and VFX pass checklist (markers, tracking, hdr plates).",
    category: "video",
    tags: ["vfx", "cinematography", "video", "production"],
    votes: 111,
    author: "developer",
    createdAt: "2025-11-03",
  },
  {
    id: "116",
    title: "Interview Questions + Scoring Rubric",
    description: "Role-specific interview question set with scoring rubric and ideal answers.",
    content: "Role: [position]. Create 12 interview questions (behavioral + technical), ideal answers or checklist, scoring rubric (0-3 per answer), and red flags for automatic disqualification.",
    category: "automation",
    tags: ["hr", "interview", "hiring", "rubric"],
    votes: 95,
    author: "developer",
    createdAt: "2025-11-03",
  },
  {
    id: "117",
    title: "Ecommerce Product Page Copy + SEO",
    description: "High-converting product page copy with SEO-friendly descriptions and bullets.",
    content: "Product: [product name]. Generate: short hero description (<=20 words), 5 benefit-driven bullets, long product description (300-400 words), SEO title & meta description, and 3 search queries to target.",
    category: "text",
    tags: ["ecommerce", "copy", "seo", "product"],
    votes: 156,
    author: "developer",
    createdAt: "2025-11-03",
  },
  {
    id: "118",
    title: "Dataset Cleaning Steps for ML",
    description: "Step-by-step data cleaning and feature prep plan for a raw dataset.",
    content: "Dataset: [describe columns]. Goal: [predict/cluster]. Provide cleaning steps (missing values, outliers), feature engineering ideas, normalization/scaling choices, train/validation split suggestions, and sample Python snippets.",
    category: "code",
    tags: ["ml", "data", "dataset", "python"],
    votes: 140,
    author: "developer",
    createdAt: "2025-11-03",
  }
];

export const allTags = [
  "trending",
  "portrait",
  "photography",
  "youtube",
  "scripting",
  "content",
  "cinematic",
  "b-roll",
  "video",
  "react",
  "typescript",
  "component",
  "email",
  "marketing",
  "automation",
  "fantasy",
  "character",
  "art",
  "sql",
  "database",
  "product",
  "launch",
  // extended tags (merged)
  "resume",
  "seo",
  "ads",
  "prompt-engineering",
  "shorts",
  "ui",
  "chatbot",
  "data-viz",
  "branding",
  "onboarding",
  "education",
  "pitch",
  "vfx",
  "interview",
  "ecommerce",
  "ml",
  "ux",
  "copy",
  "b2b"
];

export const categories = [
  { value: "image", label: "Image Generation" },
  { value: "video", label: "Video Production" },
  { value: "text", label: "Text & Writing" },
  { value: "code", label: "Code & Development" },
  { value: "automation", label: "Automation & Workflow" },
];

